var default_core_language = {
	'_inventory': "Body parts/Bindings",
	'_objects': "Objects",
	'_pick_action': "Pick an action below",
	'_pick_target_0_of_1': "{0}",
	'_pick_target_1_completed': "{0} {1}",
	'_pick_target_0_of_2': "{0}",
	'_pick_target_1_of_2': "{0} {1} {2}",
	'_pick_target_2_completed': "{0} {1} {3} {2}",
	'_pick_target_linker': "with",
	'_you_cant_do_that': "You can't do that!",
	'_hint_{0}': "Hint {0}",
	'_click_to_close': "(click to close)",
	'_start_game': "Let's start!",
	'_try_again': "Try again",
};